server:
  port: 8080
  servlet:
    context-path: /home
fulldev:
  api-package: com.example.fulldev.api
  security:
    jwt-key: jianlong
    token-expired-in: 86400000

order:
  max-sku-limit: 12
  max-sku-paytime-limit: 12
missyou:
  year-codes: 12

profiles:
  active: dev

spring:
  datasource:
    url: jdbc:mysql://123.206.232.185:3306/sleeve?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Jianlong123.
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  rabbitmq:
    addresses: 123.206.232.185:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true
    publisher-confirms: true
  redis:
    host: 123.206.232.185
    port: 6379
    password: redis123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    database: 7
  thymeleaf:
    prefix: classpath:/templates/
wx:
  appid: wx3b3d035d2db4460f
  appsecret: df2b93d5002c277293d86c4b8168f9f1
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code

